version: 2.1
jobs:
  compile:
    docker:
      - image: xyzuan/xdocker:latest
    steps:
      - run:
          command: |
            apt update && apt upgrade -y && apt install gcc-4.9 && apt upgrade libstdc++6
            curl https://raw.githubusercontent.com/cbendot/ci-script/ci-gcc/build.sh > run.sh
            source run.sh
          no_output_timeout: 5h
    # The resource_class feature allows configuring CPU and RAM resources for each job. Different resource classes are available for different executors. https://circleci.com/docs/2.0/configuration-reference/#resourceclass
    resource_class: large
workflows:
  version: 2.1
  cooking:
    jobs:
      - compile