version: 2.1
jobs:
  compile:
    docker:
      - image: xyzuan/xdocker:latest
    steps:
      - run:
          command: | 
            git clone https://$GH_TOKEN@gihub.com/cbendot/ci-script.git -b tc-build
            cd ci-script.git
            cp -af sources.list /etc/apt/
            apt-get autoremove -y && apt-get --purge remove -y && apt-get autoclean -y && apt-get update -y && apt-get upgrade -y
            apt-get install -y bc binutils-dev bison build-essential ca-certificates ccache clang cmake curl file flex git libelf-dev libssl-dev lld make ninja-build python3-dev texinfo u-boot-tools xz-utils zlib1g-dev
            curl https://raw.githubusercontent.com/cbendot/ci-script/ci-tcbuild/build.sh > run.sh
            source run.sh
          no_output_timeout: 5h
    # The resource_class feature allows configuring CPU and RAM resources for each job. Different resource classes are available for different executors. https://circleci.com/docs/2.0/configuration-reference/#resourceclass
    resource_class: large
workflows:
  version: 2.1
  cooking:
    jobs:
      - compile
