version: 2.1
jobs:
  compile:
   docker:
      - image: xyzuan/xdocker:latest
   steps:
      - run:
          command: |
            git clone https://github.com/cbendot/tcbuild $(pwd)/llvm-tc -b llvm-tc    
cd $(pwd)/llvm-tc
bash build-tc.sh
          no_output_timeout : 5h
workflows:
  version: 2.1
  cooking:
    jobs:
      - compile 
