version: 2.1
jobs:
  compile:
   docker:
      - image: xyzuan/xdocker:latest
   steps:
      - run:
          command: |
            git clone https://github.com/cbendot/tcbuild $(pwd)/llvm-tc -b llvm-tc    
            curl https://raw.githubusercontent.com/cbendot/tcbuild/llvm-tc/build-tc.sh > run.sh
            source run.sh
          no_output_timeout : 5h
workflows:
  version: 2.1
  cooking:
    jobs:
      - compile 
